### ISSUE TITLE
Warning that login file is missing

### ISSUE THREAD

**Issue by forenta** [RPDJF/steam-updater-script#1]
I'm wondering about this:

`if(Test-Path "login.xml")
{ 
    Write-Host "Please create a clixml login.xml (read the readme.md)"
    pause
    exit
}`

Shouldn't it be the other way around? This part gives the error message if the login.xml exists which is necessary according to the readme!?

**Comment by RPDJF** [comment]
You're right, my apologies, i'll change it right now
